export const Flashsaleitems = [
  {
    id: 1,
    item_name: 'Hoodie vert Rose',
    item_pricenew: '59.00',
    item_priceold: '100.00',
    item_sold: '253',
    image: require('../assets/PinkHoodie.jpg'),
    bg_color: '#FBE8E7',
    favourite: false,
    discount: '30',
    stock: 330,
  },
  {
    id: 2,
    item_name: 'Iphone 12',
    item_pricenew: '776.00',
    item_priceold: '1000.00',
    item_sold: '703',
    image: require('../assets/appleiphone.jpg'),
    bg_color: '#E7DDFF',
    favourite: true,
    discount: '31',
    stock: 1000,
  },
  {
    id: 3,
    item_name: 'Apple Watch 7',
    item_pricenew: '260.00',
    item_priceold: '269.00',
    item_sold: '236',
    image: require('../assets/applewatch.jpg'),
    bg_color: '#666666',
    favourite: false,
    discount: '33',
    stock: 500,
  },
  {
    id: 4,
    item_name: 'Keychron Q1 QMK',
    item_pricenew: '169.00',
    item_priceold: '179.00',
    item_sold: '113',
    image: require('../assets/keyboard.jpg'),
    bg_color: '#336655',
    favourite: false,
    discount: '33',
    stock: 1000,
  },
];
